### ISSUE TITLE
Pickle loading error when basenet option is specified in Pytorch SSD300 object detection sample

### ISSUE THREAD

**Issue by tdsk108** [openvinotoolkit/nncf#916] opened 2021-09-03 05:17 UTC
Hello, 
I am trying to run [Pytorch SSD300 object detection samples](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/object_detection/README.md). I could finish to run with  ssd300_vgg_voc_int8.json in the steps as shown below. However, when I used ssd300_vgg_voc.json, it failed with the following errors. (Please review the attached [log.txt](https://github.com/openvinotoolkit/nncf/files/7103498/log.txt) for detail.)
 `_pickle.UnpicklingError: global 'torch._utils._rebuild_tensor' is forbidden`
If I removed basenet option from the config file. I could finish to run without the error. 

**Questions**:
1.  Is ssd300_vgg_voc.json correct and working with NNCF v2.0.0? 
2.  Is basenet option mandatory when SSD300/SSD512 config are used in this sample?  
      It looks the following config includes the basenet option. But, others does not.
       ssd300_vgg_voc.json, ssd512_vgg_voc.json,  ssd300_vgg_voc_pruning_geometric_median.json
3.  If it is mandatory to set basenet option, do you have any idea to resolve the above error for pickle?

**Configuration**:
Python 3.6.9
Pytorch 1.8.1+cu10.2
Ubuntu 18.04.4
pickle 4.0

**Steps to run**:
```
git clone https://github.com/openvinotoolkit/nncf -b v2.0.0
cd nncf
python3 -m venv nncf
source nncf/bin/activate
pip3 install -U pip
pip3 install nncf
pip3 install pygraphviz
cd examples/torch
pip3 install -r requirements.txt
cd object_detection
export PYTHONPATH=<NNCF root dir>:$PYTHONPATH
python3 main.py -m train --config configs/ssd300_vgg_voc_int8.json --data  <path_to_dataset> --log-dir=../../results/quantization/ssd300_int8 --batch-size 8 
```
Failed when replacing to ssd300_vgg_voc.json
```
wget https://download.pytorch.org/models/vgg16_bn-6c64b313.pth
python3 main.py -m train --config configs/ssd300_vgg_voc.json --data  <path_to_dataset> --log-dir=../../results/quantization/ssd300 --batch-size 8 
```

**Comment by kshpv** [comment] 2021-10-21 10:36
Dear @tdsk108, 

Thank you for your report and sorry for the long reply.
I could reproduce your problem. The PR, which should fix the issue is opened - [989 ](https://github.com/openvinotoolkit/nncf/pull/989)
 
Thank you!

**Comment by tdsk108** [comment] 2021-11-05 12:03
Hi @kshpv,

Thank you for your support! 

Best Regards,
Toya

**Comment by kshpv** [comment] 2021-11-08 08:39
Hello, @tdsk108!

Does it fix the issue?

**Comment by dtoya** [comment] 2021-11-08 15:15
Hi @kshpv,

Thank you for your support. I confirmed the issue was fixed in the developer branch today. I observed several warnings 
as shown in [log-updated.txt](https://github.com/openvinotoolkit/nncf/files/7497961/log-updated.txt)

Is it ok to ignore the following message in line 75? 

```
WARNING:nncf:Error(s) when loading model parameters:
        Unexpected key(s):
                "classifier.0.weight",
                "classifier.6.weight",
                "classifier.6.bias",
                "classifier.3.bias",
                "classifier.3.weight",
                "classifier.0.bias".
        Missing key(s):
                "21.num_batches_tracked",
                "44.bias",
                "47.weight",
                          :
```

Best Regards,
Toya

**Comment by kshpv** [comment] 2021-11-08 15:25
> Hi @kshpv,
> 
> Thank you for your support. I confirmed the issue was fixed in the developer branch today. I observed several warnings as shown in [log-updated.txt](https://github.com/openvinotoolkit/nncf/files/7497961/log-updated.txt)
> 
> Is it ok to ignore the following message in line 75?
> 
> ```
> WARNING:nncf:Error(s) when loading model parameters:
>         Unexpected key(s):
>                 "classifier.0.weight",
>                 "classifier.6.weight",
>                 "classifier.6.bias",
>                 "classifier.3.bias",
>                 "classifier.3.weight",
>                 "classifier.0.bias".
>         Missing key(s):
>                 "21.num_batches_tracked",
>                 "44.bias",
>                 "47.weight",
>                           :
> ```
> 
> Best Regards, Toya

In your case only backbone layers was loaded, if you would like to load all ssd300-vgg-voc weights you should try `--weights` option and provide pre-trained ssd-300-vgg-voc checkpoint. You can download it from here - https://storage.openvinotoolkit.org/repositories/nncf/models/develop/ssd300_vgg_voc.pth

**Comment by kshpv** [comment] 2021-11-22 15:03
> Hi @kshpv,
> 
> Thank you for your support. I confirmed the issue was fixed in the developer branch today. I observed several warnings as shown in [log-updated.txt](https://github.com/openvinotoolkit/nncf/files/7497961/log-updated.txt)
> 
> Is it ok to ignore the following message in line 75?
> 
> ```
> WARNING:nncf:Error(s) when loading model parameters:
>         Unexpected key(s):
>                 "classifier.0.weight",
>                 "classifier.6.weight",
>                 "classifier.6.bias",
>                 "classifier.3.bias",
>                 "classifier.3.weight",
>                 "classifier.0.bias".
>         Missing key(s):
>                 "21.num_batches_tracked",
>                 "44.bias",
>                 "47.weight",
>                           :
> ```
> 
> Best Regards, Toya

Hello, Toya!

Did you resolve your issue?

**Comment by tdsk108** [comment] 2021-11-24 07:33
Hi @kshpv,

Thank you for keep following up and sorry for being late to reply. I added the option "--weights" with the checkpoint file. Although the checkpoint is loaded, I observed the following warnings instead as shown 
[log-update2.txt](https://github.com/openvinotoolkit/nncf/files/7593553/log-update2.txt)


```
WARNING:nncf:Error(s) when loading model parameters:
        Unexpected key(s):
                "scheduler",
                "iter",
                "optimizer",
                "state_dict".
        Missing key(s):
                "basenet.45.num_batches_tracked",
                "basenet.4.weight",
                "basenet.41.bias",
                "extras.16.weight",
                "basenet.45.running_var",
                "extras.6.weight",
                "extras.13.running_var",
                "detection_head.heads.5.conf.weight",
                "basenet.8.weight",
                "extras.1.running_mean",
                "extras.16.running_mean",
                "basenet.44.weight",
                "extras.13.num_batches_tracked",
                "extras.9.weight",

```

Best Regards,
Toya

**Comment by kshpv** [comment] 2021-11-24 20:47
@tdsk108,

Please, rebase NNCF on the latest develop branch. You are using the version with the bug that was recently fixed.
Then try the command that you used above once again and it should work fine.
Please, let me know, if it works.

**Comment by kshpv** [comment] 2021-11-26 08:54
Hi, @tdsk108!
Did you try on the last develop branch?

**Comment by tdsk108** [comment] 2021-11-26 14:17
Hi @kshpv,

I confirmed that the bug was fixed in the latest developer branch [log-update3.txt](https://github.com/openvinotoolkit/nncf/files/7609222/log-update3.txt) .    Please kindly close this issue. Thank you for your great support!

Best Regards,
Toya

**Comment by kshpv** [comment] 2021-11-26 14:23
@tdsk108, not a big deal!

You are always welcome for any feedback on NNCF as well as contributions!

Best,
Aleksei

**Closed by kshpv** 2021-11-26 14:23 UTC
