### ISSUE TITLE
Two question during using retinanet_r50_fpn_1x_int8 in mmdetection

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf#143] opened 2020-09-19 02:02 UTC
When I trying to train retinanet_r50_fpn_1x_int8 demo in mmdetection, training process has no problem, when it come into evaluation it encounter problem as follows:

  File "/home/amax/projects/mech_learning/tools/train.py", line 216, in main
    meta=meta)
  File "/home/amax/projects/mech_learning/mmdet/apis/train.py", line 149, in train_detector
    compression_ctrl=compression_ctrl)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
    self.call_hook('after_train_epoch')
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/amax/projects/mech_learning/mmdet/core/evaluation/eval_hooks.py", line 27, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/amax/projects/mech_learning/mmdet/apis/test.py", line 36, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/amax/git_projects/nncf_pytorch/nncf/dynamic_graph/wrappers.py", line 81, in wrapped
    return module_call(self, *args, **kwargs)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/amax/git_projects/nncf_pytorch/nncf/dynamic_graph/wrappers.py", line 81, in wrapped
    return module_call(self, *args, **kwargs)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amax/git_projects/nncf_pytorch/nncf/debug.py", line 82, in decorated
    retval = forward_func(self, *args, **kwargs)
  File "/home/amax/git_projects/nncf_pytorch/nncf/nncf_network.py", line 366, in forward
    retval = self.get_nncf_wrapped_model()(*args, **kwargs)
  File "/home/amax/git_projects/nncf_pytorch/nncf/dynamic_graph/wrappers.py", line 83, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/amax/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amax/projects/mech_learning/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/amax/projects/mech_learning/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/amax/projects/mech_learning/mmdet/models/detectors/base.py", line 156, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/amax/projects/mech_learning/mmdet/models/detectors/single_stage.py", line 111, in simple_test
    *outs, img_metas, rescale=rescale)
  File "/home/amax/projects/mech_learning/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/amax/projects/mech_learning/mmdet/models/dense_heads/anchor_head.py", line 569, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/amax/projects/mech_learning/mmdet/models/dense_heads/anchor_head.py", line 647, in _get_bboxes_single
    cfg.max_per_img)
  File "/home/amax/projects/mech_learning/mmdet/core/post_processing/bbox_nms.py", line 40, in multiclass_nms
    bboxes = bboxes[valid_mask]
  File "/home/amax/git_projects/nncf_pytorch/nncf/dynamic_graph/wrappers.py", line 41, in wrapped
    result = operator_info.custom_trace_fn(operator, *args, **kwargs)
  File "/home/amax/git_projects/nncf_pytorch/nncf/dynamic_graph/patch_pytorch.py", line 71, in __call__
    "input and output tensor count mismatch!".format(operator.__name__))
RuntimeError: Unable to forward trace through operator __getitem__ - input and output tensor count mismatch!

Should I set --no-validate during training?

Second question, After training one epoch i got a checkpoint file and use the same config file for evaluation, when loading the model i got this error :
unexpected key in source state_dict: nncf_module.backbone.conv1.weight, nncf_module.backbone.conv1.pre_ops.0.op._num_bits, ...
missing keys in source state_dict: backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, backbone.bn1.running_mean, ...
 So the key in model is all mismatch and result is empty:

[>>>>>>>>>>>>>>>>>>>>>>>>>>] 5000/5000, 14.3 task/s, elapsed: 350s, ETA:     0s
Evaluating bbox...
Loading and preparing results...
The testing results of the whole dataset is empty.

Is there something wrong in my operation ?

**Comment by vshampor** [comment] 2020-09-21 10:37
@aleksei-kashapov can you please take a look and update the mmdetection patch with necessary fixes?

**Comment by Wang-zipeng** [comment] 2020-09-21 11:33
> @aleksei-kashapov can you please take a look and update the mmdetection patch with necessary fixes?

I think i have been apply patch on mmdetection follow your doc, and i think have been got the newest code.
The pic as follows is all edited file in mmdetection after apply patch.
![image](https://user-images.githubusercontent.com/40973262/93761944-46da3200-fc41-11ea-864d-02bb4a9a39e8.png)

**Comment by birdsheng** [comment] 2020-09-22 02:15
Same problems. I have also checked the mmdetection patch and it is the latest one (updated 26 days ago).
Besides, could you please figure out the way to convert the .pth to .onnx? 
I refered to this issue https://github.com/openvinotoolkit/nncf_pytorch/issues/80
But it doesn't work for some reason like 'no gt_bbox'.

**Comment by shawn-xj** [comment] 2020-09-22 03:05
> Same problems. I have also checked the mmdetection patch and it is the latest one (updated 26 days ago).
> Besides, could you please figure out the way to convert the .pth to .onnx?
> I refered to this issue #80
> But it doesn't work for some reason like 'no gt_bbox'.
> Thanks.

I can train and test with no problem. Maybe it is due to the incorrect version of your MMDetection?

**Comment by aleksei-kashapov** [comment] 2020-09-22 08:18
Dear @Wang-zipeng,

I applied the mmdetection patch following the instruction and ,unfortunately, I couldn't reproduce your first problem.
At the same time I also faced the 0 accuracy related to the second question. The reason of that is a invalid config file.

I've updated the patch with new config files and verified train and test scripts with ssd_300 and retinanet_r50 models on COCO and VOC datasets. Please check it out - https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch
If you face any issue with that please let me know.

@birdsheng and @shawn-xj I am working on the export feature. I will let you know when it is ready

**Comment by Wang-zipeng** [comment] 2020-09-22 08:55
@aleksei-kashapov thank you for your apply, the first question is only myself question, just ignore it.
And i will try your new patch, thank you.

**Comment by aleksei-kashapov** [comment] 2020-09-22 12:22
Dears @birdsheng, @shawn-xj 

Please check out the updated patch that enables support of exporting NNCF-compressed model to ONNX format
https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch/third_party_integration/mmdetection

I tested export on retinanet_r50 model with int8 quantization. It seems working fine.

**Comment by shawn-xj** [comment] 2020-09-23 08:10
> Dears @birdsheng, @shawn-xj
> 
> Please check out the updated patch that enables support of exporting NNCF-compressed model to ONNX format
> https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch/third_party_integration/mmdetection
> 
> I tested export on retinanet_r50 model with int8 quantization. It seems working fine.

Hi,
Thanks for your reply.
I've tried the latest patch you provided. There are still some errors occur during the exporting process.
In the pytorch2onnx.py file, "opset_version=10" is fixed in "torch.onnx.export" function (line 62). However, the RuntimeError shows that:
Exporting the operator masked_select to ONNX opset version 10 is not supported . Support for this operator was added in version 11, try exporting with this version.

I noticed that "opset version" is set to default value 11 in the original code of mmdeteciton. So I changed it and the ONNX model was generated succesfully. However, when using openvino mo.py to generate .xml and .bin model, another error occurs:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.load.onnx.loader.ONNXLoader'>): Unexpected exception happened during extracting attributes for node Resize_193.
Original exception message: ONNX Resize operation from opset 11 is not supported.

It seems that the problem is not fully addressed. Could you please check it out? Thanks again.

**Comment by shawn-xj** [comment] 2020-09-24 03:11
> Dears @birdsheng, @shawn-xj
> 
> Please check out the updated patch that enables support of exporting NNCF-compressed model to ONNX format
> https://github.com/aleksei-kashapov/nncf_pytorch/tree/update_mmdet_patch/third_party_integration/mmdetection
> 
> I tested export on retinanet_r50 model with int8 quantization. It seems working fine.

Hi,
Thanks for your reply.
After applying the latest patch, I can now successfully export .onnx model. However, errors occur again when using openvino to generate the IR model by using mo.py.

mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.output_cut.OutputCut'>): Graph contains 0 node after executing <class 'extensions.front.output_cut.OutputCut'>. It considered as error because resulting IR will be empty which is not usual

I have checked the DUBUG log, it seems that all nodes from .onnx model are treated as dead nodes and removed during the process.

**Comment by kchechil** [comment] 2020-11-20 09:15
@aleksei-kashapov please answer the last questions.

**Comment by aleksei-kashapov** [comment] 2020-11-30 09:42
@shawn-xj 

Our patch for mmdetection is just a simple demonstration of how to include NNCF into a big project. This patch doesn't aim to provide a full function to a user. It is just a demonstration.

If you would like to get full NNCF support in mmdetection I highly recommend you to use mmdetection fork, on which our team is working. There is a readme that expresses instructions on how to export a model to ONNX or OpenVINO and to evaluate these models.

In our mmdetection fork we've already covered retinanet_r50_fpn_1x model

**Comment by aleksei-kashapov** [comment] 2020-12-21 13:52
@shawn-xj 

I've updated mmdet patch and it is possible now to convert models to onnx via mmdet pytorch2onnx.py script. However, even mmdet team has some problems with exporting original retinanet to onnx without any compression. See this issue https://github.com/open-mmlab/mmdetection/issues/4203#issuecomment-748695867

So, you can try, but I highly recommend using our mmdet fork OpenVINO model deployment, which I indicated before.

**Closed by aleksei-kashapov** 2020-12-21 13:52 UTC
