### ISSUE TITLE
BUG : onnx export bug for multiple inputs quantization

### ISSUE THREAD

**Issue by raymon-tian** [openvinotoolkit/nncf#486] opened 2021-02-04 09:41 UTC
Hi, thanks for your great work.

when I export my model with multiple quantized inputs to onnx graph following the below configs, both `FakeQuantize` and `QuantizeLinear/DequantizeLinear` quantizers are inserted after the input node.

```
        "input_info":[
            {
                "sample_size": [1, 1, 512, 512],
            },
            {
                "sample_size": [1, 1, 512, 512],
            },
          ],
        "quantizer_setup_type": "pattern_based",
        "compression":
            {
                "algorithm": "quantization",
                "export_to_onnx_standard_ops": true,
                "quantize_inputs" : true,
                }
            }
```
![image](https://user-images.githubusercontent.com/16444430/106873978-01aa2e80-6710-11eb-97d7-ffd9117025f5.png)
it may be a bug?

**Comment by AlexKoff88** [comment] 2021-02-04 10:39
@raymon-tian, thanks for your interest! This is obviously an unexpected behavior and should be fixed. We moved to propagation-based mode for FQ quantizer insertion and already made it a default option. 
Can you please try to remove `"quantizer_setup_type": "pattern_based"` from the config and try to quantize and export the model again?

**Comment by raymon-tian** [comment] 2021-02-07 02:47
@AlexKoff88, thanks for your reply and sorry I'm late reply. After I moved the `"quantizer_setup_type": "pattern_based"` from my config, a RuntimeError is raised : RuntimeError : Quantization parameter constraints specified in NNCF config are incompatible with HW capabilities as specified in HW config type "CPU"。

**Comment by AlexKoff88** [comment] 2021-02-07 10:13
I guess you should also remove `"quantize_inputs" : true` in this case so your new config should be as follows:
```         
        "input_info":[
            {
                "sample_size": [1, 1, 512, 512],
            },
            {
                "sample_size": [1, 1, 512, 512],
            },
         ],
         "compression":
         {
              "algorithm": "quantization",
             "export_to_onnx_standard_ops": true
         }
```

cc'ed @vshampor, @ljaljushkin

**Comment by vshampor** [comment] 2021-03-29 08:23
Closing this since the pattern based quantization mode has been removed from NNCF.

**Closed by vshampor** 2021-03-29 08:23 UTC
