### ISSUE TITLE
[BUG] Returning the input to an Upsample layer crashes `nncf.quantize`

### ISSUE THREAD

**Issue by basioli-k** [openvinotoolkit/nncf#2374] opened 2024-01-08 12:02 UTC
**NNCF version**
`2.7.0`

**Problem**
I am attempting to quantize a pytorch model with a `torch.nn.Upsample` layer.
I want to pass an input to the forward function of `upsample` and return the input to the operation and the upsampled output.

NOTE 1: that this problem only occurs if I set `quantize_outputs` from `AdvancedQuantizationParameters` to `true`.
NOTE 2: If I use `conv2d` instead of `upsample` this problem doesn't occur.

**Expected behavior**
`nncf.quantize` executes correctly giving me output quantization parameters and input quantization parameters.

**Actual behavior**
`nncf.quantize` crashes with:
```
  File "/usr/local/lib/python3.10/dist-packages/nncf/torch/dynamic_graph/context.py", line 275, in execute_pre_hooks
    op_inputs[input_arg_to_process] = hook(op_inputs[input_arg_to_process])
  File "/usr/local/lib/python3.10/dist-packages/nncf/torch/quantization/external_quantizer.py", line 39, in __call__
    storage = getattr(replica.nncf, EXTERNAL_QUANTIZERS_STORAGE_NAME)
AttributeError: 'NoneType' object has no attribute 'nncf'
```

**Reproduction steps with minimal example**
Run the following code:
```
import torch
import nncf
import numpy as np
from nncf.parameters import TargetDevice
from nncf.quantization.advanced_parameters import AdvancedQuantizationParameters, OverflowFix
from nncf.quantization.advanced_parameters import QuantizationParameters as NNCFQuantizationParameters
from nncf.quantization.range_estimator import RangeEstimatorParametersSet

class DummyDataset(torch.utils.data.Dataset):
    """ Loads images from a folder """
    def __init__(self, input_shapes, input_names):
        self.input_shapes = input_shapes
        self.input_names = input_names

    def __len__(self):
        return 1

    def __getitem__(self, index):
        return { self.input_names[i]: np.random.rand(*input_shape) for i, input_shape in enumerate(self.input_shapes) }

class ExampleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.upsample = torch.nn.Upsample(mode="nearest", scale_factor=2)
        # self.upsample = torch.nn.Conv2d(in_channels=2, out_channels=3, kernel_size=1, stride=1)

    def forward(self, input):
        res1 = self.upsample(input)

        return res1, input

inputs = [torch.randn(1, 2, 144, 240)]
input_names = ["input"]

def transform_fn(data):
    data_dict = data
    return tuple(data_dict[key][0].to(torch.float32) for key in data_dict)

dummy_dl = torch.utils.data.DataLoader(DummyDataset([inp.shape for inp in inputs], input_names))
calibration_dataset = nncf.Dataset(dummy_dl, transform_fn)

advanced_parameters = AdvancedQuantizationParameters(overflow_fix=OverflowFix.DISABLE, 
                        quantize_outputs=True,
                        disable_bias_correction=True,
                        activations_quantization_params=NNCFQuantizationParameters(8, "asymmetric", per_channel=False),
                        weights_quantization_params=NNCFQuantizationParameters(8, "symmetric"),
                    )
quantized_model = nncf.quantize(ExampleModel(), calibration_dataset, subset_size=1, preset=nncf.QuantizationPreset.MIXED, target_device=TargetDevice.GPU,
    fast_bias_correction=True, advanced_parameters=advanced_parameters)
```

**Comment by alexsu52** [comment] 2024-01-09 12:11
@AlexanderDokuchaev, can you take a look?

**Comment by AlexanderDokuchaev** [comment] 2024-01-09 12:54
@basioli-k Thanks to provide code, this problem is actual for v270. But issues is not reproduced on `develop` and `release_v280` branches. 
Try to install NCCF from `develop` branch by `pip install git+https://github.com/openvinotoolkit/nncf.git@develop`, release NNCF 2.8.0 coming soon.

**Comment by MaximProshin** [comment] 2024-10-01 10:03
Closed as no feedback for a long time period while it's assumed that the problem is not reproduced in newer NNCF versions. Feel free to reopen it if needed.

**Closed by MaximProshin** 2024-10-01 10:03 UTC
