### ISSUE TITLE
ERROR:nncf:Invalid NNCF config supplied!

### ISSUE THREAD

**Issue by SiChuanJay** [openvinotoolkit/nncf#1594] opened 2023-02-23 06:57 UTC
Hello, I encountered the following problems when running this project ( https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/302-pytorch-quantization-aware-training ) . May I ask how to modify this
![图片](https://user-images.githubusercontent.com/52130681/220838771-06b19076-54ca-44f7-b14b-84b4fc4e3994.png)

Thanks for your help

**Comment by SiChuanJay** [comment] 2023-02-23 09:05
![图片](https://user-images.githubusercontent.com/52130681/220862658-060da86b-b7b0-465c-8493-df4511b4d9e4.png)
![图片](https://user-images.githubusercontent.com/52130681/220862742-5ac70cdb-7182-411b-8f07-4e9cbb009acd.png)

There seems to be something wrong with the nncf config

**Comment by ljaljushkin** [comment] 2023-02-23 10:19
Hello @SiChuanJay!

Unfortunately, I can't reproduce the issue. 
I've followed the instructions for Ubuntu here: https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu
My guess that it might the issue whether with versions or with miniconda.
Do you configure the python environment differently?
Could you also try not using miniconda and create a virtual environment using a system-wide python? Will everything work in your case?

**Comment by ljaljushkin** [comment] 2023-02-23 10:20
Would be also helpful if you collect the list of python packages in your environment `pip list > packages.txt` and send the file.

**Comment by SiChuanJay** [comment] 2023-02-23 11:57
[packages.txt](https://github.com/openvinotoolkit/nncf/files/10813195/packages.txt)

Please take a look, thanks!

**Comment by ljaljushkin** [comment] 2023-02-23 12:12
> [packages.txt](https://github.com/openvinotoolkit/nncf/files/10813195/packages.txt)
> 
> Please take a look, thanks!

Looks normal, can't catch some issues with versions. 
The NNCFConfig is also looking correct. 

Could you share how exactly you installed the python environment and how you run the notebook? It might help to reproduce the issue.

**Comment by SiChuanJay** [comment] 2023-02-23 12:13
![图片](https://user-images.githubusercontent.com/52130681/220902064-facbc06a-7788-4b7a-b726-fb7df766e375.png)

When I comment out "compression" and the subsequent parameters, there is no error. It should be this parameter.

**Comment by ljaljushkin** [comment] 2023-02-23 12:21
Could you copy-paste the config that you use? Can it by any chance contain some modifications on top of original version?

**Comment by SiChuanJay** [comment] 2023-02-23 12:25
nncf_config_dict = {
    "input_info": {
        
        "sample_size": [1, 3, 64, 64]
        },
    "log_dir": str(OUTPUT_DIR),  # The log directory for NNCF-specific logging outputs.
    "compression": {
        "algorithm": "quantization",  # Specify the algorithm here.
    },
}
nncf_config = NNCFConfig.from_dict(nncf_config_dict)


I followed notebook's steps  https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/302-pytorch-quantization-aware-training

**Comment by ljaljushkin** [comment] 2023-02-23 12:48
> Do you configure the python environment differently? Could you also try not using miniconda and create a virtual environment using a system-wide python? Will everything work in your case?

> Could you share how exactly you installed the python environment and how you run the notebook? It might help to reproduce the issue.

Please share answers for the previous questions

**Comment by SiChuanJay** [comment] 2023-02-23 12:55
My environment was installed on the server via miniconda. Then connect to the environment on the server using ssh using vscode.
![图片](https://user-images.githubusercontent.com/52130681/220912400-0d9f5eaf-10ac-4bf1-8f64-1d192582ab8f.png)

**Comment by SiChuanJay** [comment] 2023-02-23 13:39
thanks for your help, I had no problems in the local environment.

**Comment by ljaljushkin** [comment] 2023-02-23 15:07
@SiChuanJay could you elaborate, what do you mean by local environment? Trying to understand the difference with a problematic environment that you had.

**Comment by SiChuanJay** [comment] 2023-02-24 01:13
Previously, the code was running in the miniconda environment in linux, and there was an error. I used a pure python environment on windows and had no problems.

I would like to ask which quantization method yolo8 matches better? pot or training-time?

**Comment by MaximProshin** [comment] 2023-03-10 05:28
@SiChuanJay , I think we can close this issue as your original problem with the environment is resolved now. Do you have any objections?
As for your question about post-training vs training-time quantization, the first method is much faster and we recommend it as the first step. In most cases it gives good accuracy results but if you want to achieve even better accuracy we recommend the training-aware quantization.

**Comment by MaximProshin** [comment] 2023-03-16 05:39
I close it as I think it was resolved. Otherwise, feel free to contact us.

**Closed by MaximProshin** 2023-03-16 05:39 UTC
